use tyler;
insert into make (make_name, model_name) values ('BMW', '1 Series');
insert into make (make_name, model_name) values ('BMW', '1 Series');
insert into make (make_name, model_name) values ('Audi', '100 Wagon');
insert into make (make_name, model_name) values ('FIAT', '124 Spider');
insert into make (make_name, model_name) values ('Ram', '1500 Classic Crew Cab');
insert into make (make_name, model_name) values ('Ram', '1500 Classic Quad Cab');
insert into make (make_name, model_name) values ('Ram', '1500 Classic Regular Cab');
insert into make (make_name, model_name) values ('GMC', '1500 Club Coupe');
 insert into make (make_name, model_name) values ('Acura' , 'ILX'); 
 insert into make (make_name, model_name) values ('Acura' , 'MDX'); 
 insert into make (make_name, model_name) values ('Acura' , 'MDX Sport Hybrid'); 
 insert into make (make_name, model_name) values ('Acura' , 'NSX'); 
 insert into make (make_name, model_name) values ('Acura' , 'RDX'); 
 insert into make (make_name, model_name) values ('Acura' , 'RLX'); 
 insert into make (make_name, model_name) values ('Acura' , 'RLX Sport Hybrid'); 
 insert into make (make_name, model_name) values ('Acura' , 'TLX'); 
 insert into make (make_name, model_name) values ('Alfa Romeo' , '4C Spider'); 
 insert into make (make_name, model_name) values ('Alfa Romeo' , 'Giulia'); 
 insert into make (make_name, model_name) values ('Alfa Romeo' , 'Stelvio'); 
 insert into make (make_name, model_name) values ('Audi' , 'A3'); 
 insert into make (make_name, model_name) values ('Audi' , 'A4'); 
 insert into make (make_name, model_name) values ('Audi' , 'A5'); 
 insert into make (make_name, model_name) values ('Audi' , 'A6'); 
 insert into make (make_name, model_name) values ('Audi' , 'A6 allroad'); 
 insert into make (make_name, model_name) values ('Audi' , 'A7'); 
 insert into make (make_name, model_name) values ('Audi' , 'Q3'); 
 insert into make (make_name, model_name) values ('Audi' , 'Q5'); 
 insert into make (make_name, model_name) values ('Audi' , 'Q7'); 
 insert into make (make_name, model_name) values ('Audi' , 'Q8'); 
 insert into make (make_name, model_name) values ('Audi' , 'R8'); 
 insert into make (make_name, model_name) values ('Audi' , 'S4'); 
 insert into make (make_name, model_name) values ('Audi' , 'S8'); 
 insert into make (make_name, model_name) values ('Audi' , 'SQ5'); 
 insert into make (make_name, model_name) values ('Audi' , 'TT'); 
 insert into make (make_name, model_name) values ('BMW' , '2 Series'); 
 insert into make (make_name, model_name) values ('BMW' , '3 Series'); 
 insert into make (make_name, model_name) values ('BMW' , '4 Series'); 
 insert into make (make_name, model_name) values ('BMW' , '5 Series'); 
 insert into make (make_name, model_name) values ('BMW' , '7 Series'); 
 insert into make (make_name, model_name) values ('BMW' , '8 Series'); 
 insert into make (make_name, model_name) values ('BMW' , 'M2'); 
 insert into make (make_name, model_name) values ('BMW' , 'X1'); 
 insert into make (make_name, model_name) values ('BMW' , 'X2'); 
 insert into make (make_name, model_name) values ('BMW' , 'X3'); 
 insert into make (make_name, model_name) values ('BMW' , 'X3 M'); 
 insert into make (make_name, model_name) values ('BMW' , 'X4'); 
 insert into make (make_name, model_name) values ('BMW' , 'X5'); 
 insert into make (make_name, model_name) values ('BMW' , 'X6'); 
 insert into make (make_name, model_name) values ('BMW' , 'X7'); 
 insert into make (make_name, model_name) values ('BMW' , 'Z4'); 
 insert into make (make_name, model_name) values ('Buick' , 'Enclave'); 
 insert into make (make_name, model_name) values ('Buick' , 'Encore'); 
 insert into make (make_name, model_name) values ('Buick' , 'Encore GX'); 
 insert into make (make_name, model_name) values ('Buick' , 'Envision'); 
 insert into make (make_name, model_name) values ('Buick' , 'Regal Sportback'); 
 insert into make (make_name, model_name) values ('Buick' , 'Regal TourX'); 
 insert into make (make_name, model_name) values ('Cadillac' , 'CT4'); 
 insert into make (make_name, model_name) values ('Cadillac' , 'CT5'); 
 insert into make (make_name, model_name) values ('Cadillac' , 'CT6'); 
 insert into make (make_name, model_name) values ('Cadillac' , 'CT6-V'); 
 insert into make (make_name, model_name) values ('Cadillac' , 'Escalade'); 
 insert into make (make_name, model_name) values ('Cadillac' , 'Escalade ESV'); 
 insert into make (make_name, model_name) values ('Cadillac' , 'XT4'); 
 insert into make (make_name, model_name) values ('Cadillac' , 'XT5'); 
 insert into make (make_name, model_name) values ('Cadillac' , 'XT6'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Blazer'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Bolt EV'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Camaro'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Colorado Crew Cab'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Colorado Extended Cab'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Corvette'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Equinox'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Express 2500 Cargo'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Express 3500 Cargo'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Impala'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Malibu'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Silverado 1500 Crew Cab'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Silverado 1500 Double Cab'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Silverado 1500 Regular Cab'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Silverado 2500 HD Crew Cab'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Silverado 2500 HD Double Cab'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Silverado 3500 HD Crew Cab'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Sonic'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Spark'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Suburban'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Tahoe'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Traverse'); 
 insert into make (make_name, model_name) values ('Chevrolet' , 'Trax'); 
 insert into make (make_name, model_name) values ('Chrysler' , '300'); 
 insert into make (make_name, model_name) values ('Chrysler' , 'Pacifica'); 
 insert into make (make_name, model_name) values ('Chrysler' , 'Pacifica Hybrid'); 
 insert into make (make_name, model_name) values ('Chrysler' , 'Voyager'); 
 insert into make (make_name, model_name) values ('Dodge' , 'Challenger'); 
 insert into make (make_name, model_name) values ('Dodge' , 'Charger'); 
 insert into make (make_name, model_name) values ('Dodge' , 'Durango'); 
 insert into make (make_name, model_name) values ('Dodge' , 'Grand Caravan Passenger'); 
 insert into make (make_name, model_name) values ('Dodge' , 'Journey'); 
 insert into make (make_name, model_name) values ('FIAT' , '124 Spider'); 
 insert into make (make_name, model_name) values ('FIAT' , '500L'); 
 insert into make (make_name, model_name) values ('FIAT' , '500X'); 
 insert into make (make_name, model_name) values ('Ford' , 'EcoSport'); 
 insert into make (make_name, model_name) values ('Ford' , 'Edge'); 
 insert into make (make_name, model_name) values ('Ford' , 'Escape'); 
 insert into make (make_name, model_name) values ('Ford' , 'Expedition'); 
 insert into make (make_name, model_name) values ('Ford' , 'Expedition MAX'); 
 insert into make (make_name, model_name) values ('Ford' , 'Explorer'); 
 insert into make (make_name, model_name) values ('Ford' , 'F150 Regular Cab'); 
 insert into make (make_name, model_name) values ('Ford' , 'F150 Super Cab'); 
 insert into make (make_name, model_name) values ('Ford' , 'F150 SuperCrew Cab'); 
 insert into make (make_name, model_name) values ('Ford' , 'F250 Super Duty Crew Cab'); 
 insert into make (make_name, model_name) values ('Ford' , 'F250 Super Duty Regular Cab'); 
 insert into make (make_name, model_name) values ('Ford' , 'F250 Super Duty Super Cab'); 
 insert into make (make_name, model_name) values ('Ford' , 'F350 Super Duty Crew Cab'); 
 insert into make (make_name, model_name) values ('Ford' , 'F350 Super Duty Super Cab'); 
 insert into make (make_name, model_name) values ('Ford' , 'F450 Super Duty Crew Cab'); 
 insert into make (make_name, model_name) values ('Ford' , 'Fusion'); 
 insert into make (make_name, model_name) values ('Ford' , 'Fusion Plug-in Hybrid'); 
 insert into make (make_name, model_name) values ('Ford' , 'Mustang'); 
 insert into make (make_name, model_name) values ('Ford' , 'Ranger SuperCab'); 
 insert into make (make_name, model_name) values ('Ford' , 'Ranger SuperCrew'); 
 insert into make (make_name, model_name) values ('Ford' , 'Transit 250 Cargo Van'); 
 insert into make (make_name, model_name) values ('Ford' , 'Transit 350 Passenger Van'); 
 insert into make (make_name, model_name) values ('Ford' , 'Transit Connect Cargo Van'); 
 insert into make (make_name, model_name) values ('Ford' , 'Transit Connect Passenger Wagon'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 1500 Cargo'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 1500 Passenger'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 2500 Cargo'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 2500 Crew'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 2500 Passenger'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 3500 Cargo'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 3500 Crew'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 3500 XD Crew'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 3500XD Cargo'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 4500 Cargo'); 
 insert into make (make_name, model_name) values ('Freightliner' , 'Sprinter 4500 Crew'); 
 insert into make (make_name, model_name) values ('Genesis' , 'G70'); 
 insert into make (make_name, model_name) values ('Genesis' , 'G80'); 
 insert into make (make_name, model_name) values ('Genesis' , 'G90'); 
 insert into make (make_name, model_name) values ('GMC' , 'Acadia'); 
 insert into make (make_name, model_name) values ('GMC' , 'Canyon Crew Cab'); 
 insert into make (make_name, model_name) values ('GMC' , 'Sierra 1500 Crew Cab'); 
 insert into make (make_name, model_name) values ('GMC' , 'Sierra 1500 Double Cab'); 
 insert into make (make_name, model_name) values ('GMC' , 'Sierra 1500 Regular Cab'); 
 insert into make (make_name, model_name) values ('GMC' , 'Sierra 2500 HD Crew Cab'); 
 insert into make (make_name, model_name) values ('GMC' , 'Sierra 3500 HD Crew Cab'); 
 insert into make (make_name, model_name) values ('GMC' , 'Terrain'); 
 insert into make (make_name, model_name) values ('GMC' , 'Yukon'); 
 insert into make (make_name, model_name) values ('GMC' , 'Yukon XL'); 
 insert into make (make_name, model_name) values ('Honda' , 'Accord'); 
 insert into make (make_name, model_name) values ('Honda' , 'Accord Hybrid'); 
 insert into make (make_name, model_name) values ('Honda' , 'Civic'); 
 insert into make (make_name, model_name) values ('Honda' , 'Civic Type R'); 
 insert into make (make_name, model_name) values ('Honda' , 'Clarity Fuel Cell'); 
 insert into make (make_name, model_name) values ('Honda' , 'Clarity Plug-in Hybrid'); 
 insert into make (make_name, model_name) values ('Honda' , 'CR-V'); 
 insert into make (make_name, model_name) values ('Honda' , 'CR-V Hybrid'); 
 insert into make (make_name, model_name) values ('Honda' , 'Fit'); 
 insert into make (make_name, model_name) values ('Honda' , 'HR-V'); 
 insert into make (make_name, model_name) values ('Honda' , 'Insight'); 
 insert into make (make_name, model_name) values ('Honda' , 'Odyssey'); 
 insert into make (make_name, model_name) values ('Honda' , 'Passport'); 
 insert into make (make_name, model_name) values ('Honda' , 'Pilot'); 
 insert into make (make_name, model_name) values ('Honda' , 'Ridgeline'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Accent'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Elantra'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Elantra GT'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Ioniq Electric'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Ioniq Hybrid'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Ioniq Plug-in Hybrid'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Kona'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Kona Electric'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'NEXO'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Palisade'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Santa Fe'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Sonata'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Sonata Hybrid'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Tucson'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Veloster'); 
 insert into make (make_name, model_name) values ('Hyundai' , 'Venue'); 
 insert into make (make_name, model_name) values ('INFINITI' , 'Q50'); 
 insert into make (make_name, model_name) values ('INFINITI' , 'Q60'); 
 insert into make (make_name, model_name) values ('INFINITI' , 'QX50'); 
 insert into make (make_name, model_name) values ('INFINITI' , 'QX60'); 
 insert into make (make_name, model_name) values ('INFINITI' , 'QX80'); 
 insert into make (make_name, model_name) values ('Jaguar' , 'E-PACE'); 
 insert into make (make_name, model_name) values ('Jaguar' , 'F-PACE'); 
 insert into make (make_name, model_name) values ('Jaguar' , 'F-TYPE'); 
 insert into make (make_name, model_name) values ('Jaguar' , 'I-PACE'); 
 insert into make (make_name, model_name) values ('Jaguar' , 'XE'); 
 insert into make (make_name, model_name) values ('Jaguar' , 'XF'); 
 insert into make (make_name, model_name) values ('Jeep' , 'Cherokee'); 
 insert into make (make_name, model_name) values ('Jeep' , 'Compass'); 
 insert into make (make_name, model_name) values ('Jeep' , 'Gladiator'); 
 insert into make (make_name, model_name) values ('Jeep' , 'Grand Cherokee'); 
 insert into make (make_name, model_name) values ('Jeep' , 'Renegade'); 
 insert into make (make_name, model_name) values ('Jeep' , 'Wrangler'); 
 insert into make (make_name, model_name) values ('Jeep' , 'Wrangler Unlimited'); 
 insert into make (make_name, model_name) values ('Kia' , 'Cadenza'); 
 insert into make (make_name, model_name) values ('Kia' , 'Forte'); 
 insert into make (make_name, model_name) values ('Kia' , 'K900'); 
 insert into make (make_name, model_name) values ('Kia' , 'Niro'); 
 insert into make (make_name, model_name) values ('Kia' , 'Niro EV'); 
 insert into make (make_name, model_name) values ('Kia' , 'Niro Plug-in Hybrid'); 
 insert into make (make_name, model_name) values ('Kia' , 'Optima'); 
 insert into make (make_name, model_name) values ('Kia' , 'Optima Hybrid'); 
 insert into make (make_name, model_name) values ('Kia' , 'Optima Plug-in Hybrid'); 
 insert into make (make_name, model_name) values ('Kia' , 'Rio'); 
 insert into make (make_name, model_name) values ('Kia' , 'Sedona'); 
 insert into make (make_name, model_name) values ('Kia' , 'Sorento'); 
 insert into make (make_name, model_name) values ('Kia' , 'Soul'); 
 insert into make (make_name, model_name) values ('Kia' , 'Sportage'); 
 insert into make (make_name, model_name) values ('Kia' , 'Stinger'); 
 insert into make (make_name, model_name) values ('Kia' , 'Telluride'); 
 insert into make (make_name, model_name) values ('Land Rover' , 'Defender 110'); 
 insert into make (make_name, model_name) values ('Land Rover' , 'Defender 90'); 
 insert into make (make_name, model_name) values ('Land Rover' , 'Discovery'); 
 insert into make (make_name, model_name) values ('Land Rover' , 'Discovery Sport'); 
 insert into make (make_name, model_name) values ('Land Rover' , 'Range Rover'); 
 insert into make (make_name, model_name) values ('Land Rover' , 'Range Rover Evoque'); 
 insert into make (make_name, model_name) values ('Land Rover' , 'Range Rover Sport'); 
 insert into make (make_name, model_name) values ('Land Rover' , 'Range Rover Velar'); 
 insert into make (make_name, model_name) values ('Lexus' , 'ES'); 
 insert into make (make_name, model_name) values ('Lexus' , 'GS'); 
 insert into make (make_name, model_name) values ('Lexus' , 'GX'); 
 insert into make (make_name, model_name) values ('Lexus' , 'IS'); 
 insert into make (make_name, model_name) values ('Lexus' , 'LC'); 
 insert into make (make_name, model_name) values ('Lexus' , 'LS'); 
 insert into make (make_name, model_name) values ('Lexus' , 'LX'); 
 insert into make (make_name, model_name) values ('Lexus' , 'NX'); 
 insert into make (make_name, model_name) values ('Lexus' , 'RC'); 
 insert into make (make_name, model_name) values ('Lexus' , 'RX'); 
 insert into make (make_name, model_name) values ('Lexus' , 'UX'); 
 insert into make (make_name, model_name) values ('Lincoln' , 'Aviator'); 
 insert into make (make_name, model_name) values ('Lincoln' , 'Continental'); 
 insert into make (make_name, model_name) values ('Lincoln' , 'Corsair'); 
 insert into make (make_name, model_name) values ('Lincoln' , 'MKZ'); 
 insert into make (make_name, model_name) values ('Lincoln' , 'Nautilus'); 
 insert into make (make_name, model_name) values ('Lincoln' , 'Navigator'); 
 insert into make (make_name, model_name) values ('Lincoln' , 'Navigator L'); 
 insert into make (make_name, model_name) values ('MAZDA' , 'CX-3'); 
 insert into make (make_name, model_name) values ('MAZDA' , 'CX-30'); 
 insert into make (make_name, model_name) values ('MAZDA' , 'CX-5'); 
 insert into make (make_name, model_name) values ('MAZDA' , 'CX-9'); 
 insert into make (make_name, model_name) values ('MAZDA' , 'MAZDA3'); 
 insert into make (make_name, model_name) values ('MAZDA' , 'MAZDA6'); 
 insert into make (make_name, model_name) values ('MAZDA' , 'MX-5 Miata'); 
 insert into make (make_name, model_name) values ('MAZDA' , 'MX-5 Miata RF'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'A-Class'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'C-Class'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'CLA'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'CLS'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'E-Class'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'G-Class'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'GLA'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'GLB'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'GLC'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'GLE'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'GLS'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Mercedes-AMG A-Class'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Mercedes-AMG C-Class'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Mercedes-AMG CLS'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Mercedes-AMG GLC'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Mercedes-AMG GLC Coupe'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Metris WORKER Cargo'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Metris WORKER Passenger'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'S-Class'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'SLC'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 1500 Cargo'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 1500 Passenger'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 2500 Cargo'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 2500 Crew'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 2500 Passenger'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 3500 Cargo'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 3500 Crew'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 3500 XD Cargo'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 3500 XD Crew'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 4500 Cargo'); 
 insert into make (make_name, model_name) values ('Mercedes-Benz' , 'Sprinter 4500 Crew'); 
 insert into make (make_name, model_name) values ('MINI' , 'Clubman'); 
 insert into make (make_name, model_name) values ('MINI' , 'Countryman'); 
 insert into make (make_name, model_name) values ('MINI' , 'Hardtop 2 Door'); 
 insert into make (make_name, model_name) values ('MINI' , 'Hardtop 4 Door'); 
 insert into make (make_name, model_name) values ('Mitsubishi' , 'Eclipse Cross'); 
 insert into make (make_name, model_name) values ('Mitsubishi' , 'Mirage'); 
 insert into make (make_name, model_name) values ('Mitsubishi' , 'Mirage G4'); 
 insert into make (make_name, model_name) values ('Mitsubishi' , 'Outlander'); 
 insert into make (make_name, model_name) values ('Mitsubishi' , 'Outlander PHEV'); 
 insert into make (make_name, model_name) values ('Mitsubishi' , 'Outlander Sport'); 
 insert into make (make_name, model_name) values ('Nissan' , '370Z'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Altima'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Armada'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Frontier Crew Cab'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Frontier King Cab'); 
 insert into make (make_name, model_name) values ('Nissan' , 'GT-R'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Kicks'); 
 insert into make (make_name, model_name) values ('Nissan' , 'LEAF'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Maxima'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Murano'); 
 insert into make (make_name, model_name) values ('Nissan' , 'NV1500 Cargo'); 
 insert into make (make_name, model_name) values ('Nissan' , 'NV200'); 
 insert into make (make_name, model_name) values ('Nissan' , 'NV2500 HD Cargo'); 
 insert into make (make_name, model_name) values ('Nissan' , 'NV3500 HD Cargo'); 
 insert into make (make_name, model_name) values ('Nissan' , 'NV3500 HD Passenger'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Pathfinder'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Rogue'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Rogue Sport'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Sentra'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Titan Crew Cab'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Titan King Cab'); 
 insert into make (make_name, model_name) values ('Nissan' , 'TITAN XD Crew Cab'); 
 insert into make (make_name, model_name) values ('Nissan' , 'Versa'); 
 insert into make (make_name, model_name) values ('Porsche' , '718 Boxster'); 
 insert into make (make_name, model_name) values ('Porsche' , '718 Cayman'); 
 insert into make (make_name, model_name) values ('Porsche' , '718 Spyder'); 
 insert into make (make_name, model_name) values ('Porsche' , '911'); 
 insert into make (make_name, model_name) values ('Porsche' , 'Cayenne'); 
 insert into make (make_name, model_name) values ('Porsche' , 'Cayenne Coupe'); 
 insert into make (make_name, model_name) values ('Porsche' , 'Macan'); 
 insert into make (make_name, model_name) values ('Porsche' , 'Panamera'); 
 insert into make (make_name, model_name) values ('Porsche' , 'Taycan'); 
 insert into make (make_name, model_name) values ('Ram' , '1500 Classic Crew Cab'); 
 insert into make (make_name, model_name) values ('Ram' , '1500 Classic Quad Cab'); 
 insert into make (make_name, model_name) values ('Ram' , '1500 Crew Cab'); 
 insert into make (make_name, model_name) values ('Ram' , '1500 Quad Cab'); 
 insert into make (make_name, model_name) values ('Ram' , '2500 Crew Cab'); 
 insert into make (make_name, model_name) values ('Ram' , '3500 Crew Cab'); 
 insert into make (make_name, model_name) values ('Ram' , 'ProMaster Cargo Van'); 
 insert into make (make_name, model_name) values ('Ram' , 'ProMaster City'); 
 insert into make (make_name, model_name) values ('Subaru' , 'Ascent'); 
 insert into make (make_name, model_name) values ('Subaru' , 'BRZ'); 
 insert into make (make_name, model_name) values ('Subaru' , 'Crosstrek'); 
 insert into make (make_name, model_name) values ('Subaru' , 'Forester'); 
 insert into make (make_name, model_name) values ('Subaru' , 'Impreza'); 
 insert into make (make_name, model_name) values ('Subaru' , 'Legacy'); 
 insert into make (make_name, model_name) values ('Subaru' , 'Outback'); 
 insert into make (make_name, model_name) values ('Subaru' , 'WRX'); 
 insert into make (make_name, model_name) values ('Tesla' , 'Model 3'); 
 insert into make (make_name, model_name) values ('Tesla' , 'Model S'); 
 insert into make (make_name, model_name) values ('Tesla' , 'Model X'); 
 insert into make (make_name, model_name) values ('Tesla' , 'Model Y'); 
 insert into make (make_name, model_name) values ('Toyota' , '4Runner'); 
 insert into make (make_name, model_name) values ('Toyota' , '86'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Avalon'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Avalon Hybrid'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Camry'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Camry Hybrid'); 
 insert into make (make_name, model_name) values ('Toyota' , 'C-HR'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Corolla'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Corolla Hatchback'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Corolla Hybrid'); 
 insert into make (make_name, model_name) values ('Toyota' , 'GR Supra'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Highlander'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Highlander Hybrid'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Land Cruiser'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Mirai'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Prius'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Prius Prime'); 
 insert into make (make_name, model_name) values ('Toyota' , 'RAV4'); 
 insert into make (make_name, model_name) values ('Toyota' , 'RAV4 Hybrid'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Sequoia'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Sienna'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Tacoma Access Cab'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Tacoma Double Cab'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Tundra CrewMax'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Tundra Double Cab'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Yaris'); 
 insert into make (make_name, model_name) values ('Toyota' , 'Yaris Hatchback'); 
 insert into make (make_name, model_name) values ('Volkswagen' , 'Arteon'); 
 insert into make (make_name, model_name) values ('Volkswagen' , 'Atlas'); 
 insert into make (make_name, model_name) values ('Volkswagen' , 'Atlas Cross Sport'); 
 insert into make (make_name, model_name) values ('Volkswagen' , 'Golf'); 
 insert into make (make_name, model_name) values ('Volkswagen' , 'Golf GTI'); 
 insert into make (make_name, model_name) values ('Volkswagen' , 'Jetta'); 
 insert into make (make_name, model_name) values ('Volkswagen' , 'Jetta GLI'); 
 insert into make (make_name, model_name) values ('Volkswagen' , 'Passat'); 
 insert into make (make_name, model_name) values ('Volkswagen' , 'Tiguan'); 
 insert into make (make_name, model_name) values ('Volvo' , 'S60'); 
 insert into make (make_name, model_name) values ('Volvo' , 'S90'); 
 insert into make (make_name, model_name) values ('Volvo' , 'V60'); 
 insert into make (make_name, model_name) values ('Volvo' , 'V90'); 
 insert into make (make_name, model_name) values ('Volvo' , 'XC40'); 
 insert into make (make_name, model_name) values ('Volvo' , 'XC60'); 
 insert into make (make_name, model_name) values ('Volvo' , 'XC90'); 
