GRANT USAGE ON SCHEMA public TO master;
GRANT CONNECT ON DATABASE fly1 to master;
GRANT CREATE ON DATABASE fly1 TO master;
GRANT CREATE ON SCHEMA public TO master;
GRANT UPDATE, INSERT, SELECT, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO master;
GRANT TRUNCATE ON public."BasicFeed" TO master;
            
