create table heartbeat (
  heartbeat_id          integer
                        generated by default on null as identity,
  description             varchar(40) ,
  last_update_dt            timestamp ,
  last_update_site     varchar(5));

create unique index idxu_heartbeat on heartbeat(heartbeat_id);
exit

