CREATE TABLE "UAC_HEALTH"."HEALTH_ASSESSMENT"(
 "HEALTH_ASSESSMENT_ID" NUMBER NOT NULL,
 "GENERAL_INFO_ID" NUMBER NOT NULL,
 "PROGRAM_ID" NUMBER(9,0) NOT NULL,
 "WELL_CHILD" NUMBER(1,0),
 "NEW_MEDICATION_GIVEN" NUMBER(1,0),
 "IMMUNIZATION_GIVEN" NUMBER(1,0),
 "IMMUNIZATION_NOT_GIVEN_DUE_MC" NUMBER(1,0),
 "IMMUNIZATION_NOT_GIVEN_EXP" VARCHAR2(1000 BYTE),
 "GUIDANCE_DISCUSSED" NUMBER(1,0),
 "GUIDANCE_DISCUSSED_EXP" VARCHAR2(500 BYTE),
 "PLAN_OTHER" NUMBER(1,0),
 "PLAN_OTHER_EXP" VARCHAR2(500 BYTE),
 "ADDITIONAL_INFO" VARCHAR2(2000 BYTE),
 "DATE_CREATED" DATE NOT NULL,
 "USER_CREATED" VARCHAR2(112 BYTE) NOT NULL,
 "DATE_UPDATED" DATE NOT NULL,
 "USER_UPDATED" VARCHAR2(112 BYTE),
 "AGE_APPROPRIATE" NUMBER(1,0),
 "RECOMMENDATION_FROM_CLINICIAN" VARCHAR2(5100 BYTE),
 "COMPLAINT_SYNOPSIS" VARCHAR2(5100 BYTE),
 "EVALREASON_NEWSIGNS" NUMBER(1,0),
 "EVALREASON_WORSENED" NUMBER(1,0),
 "EVALREASON_NOIMPROVE" NUMBER(1,0),
 "EVALREASON_FOLLOWUP" NUMBER(1,0),
 "EVALREASON_OTHER" NUMBER(1,0),
 "EVALREASON_OTHER_EXP" VARCHAR2(100 BYTE),
 "EVALOUTCOME_COMPLICATION" NUMBER(1,0),
 "EVALOUTCOME_RELATEDTOINI" NUMBER(1,0),
 "EVALOUTCOME_PREVIOUSINCORRECT" NUMBER(1,0),
 "EVALOUTCOME_OTHER" NUMBER(1,0),
 "EVALOUTCOME_OTHER_EXP" VARCHAR2(100 BYTE),
 "ABNORMAL_FINDINGS" NUMBER(1,0),
 "VACCINE_OTHER_EXP" VARCHAR2(250 BYTE),
 CONSTRAINT "HEALTH_ASSESSMENT_PK" PRIMARY KEY ("HEALTH_ASSESSMENT_ID")
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
LOGGING
STORAGE ( INITIAL 65536
 NEXT 1048576
 PCTINCREASE  0
 MINEXTENTS 1
 MAXEXTENTS 2147483645
 FREELISTS 1
 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT
 FLASH_CACHE DEFAULT
 CELL_FLASH_CACHE DEFAULT)
TABLESPACE UAC01
NOCOMPRESS
/

