CREATE AUDIT POLICY UNAUTH_PAYROLL       
ACTIONS
INSERT ON customer_orders.products, UPDATE ON customer_orders.products, DELETE ON customer_orders.products
WHEN 'SYS_CONTEXT(''APP_CONTEXT'', ''APP_USER'') IN (''PAYCLERK_USER'')' EVALUATE PER STATEMENT
ONLY TOPLEVEL;

AUDIT POLICY UNAUTH_PAYROLL EXCEPT admin;

