create schema jeffdm;

-- ------------ Write DROP-CONSTRAINT-stage scripts -----------

ALTER TABLE jeffdm.esrifeatureclass DROP CONSTRAINT sys_c0010246;

ALTER TABLE jeffdm.gdelttest DROP CONSTRAINT sys_c0010248;

-- ------------ Write DROP-INDEX-stage scripts -----------

DROP INDEX IF EXISTS jeffdm.shape_142114_2_sidx;

DROP INDEX IF EXISTS jeffdm.shape_142143_2_sidx;

DROP INDEX IF EXISTS jeffdm.mdrt22b36_idx1;

DROP INDEX IF EXISTS jeffdm.mdrt22b4d_idx1;

-- ------------ Write DROP-TABLE-stage scripts -----------

DROP TABLE IF EXISTS jeffdm.esrifeatureclass;

DROP TABLE IF EXISTS jeffdm.gdelttest;

DROP TABLE IF EXISTS jeffdm.mdrt_22b36$;

DROP TABLE IF EXISTS jeffdm.mdrt_22b4d$;

-- ------------ Write DROP-SEQUENCE-stage scripts -----------

DROP SEQUENCE IF EXISTS jeffdm.mdrs_22b36$;

DROP SEQUENCE IF EXISTS jeffdm.mdrs_22b4d$;

-- ------------ Write DROP-DATABASE-stage scripts -----------

-- ------------ Write CREATE-DATABASE-stage scripts -----------

CREATE SCHEMA IF NOT EXISTS jeffdm;

-- ------------ Write CREATE-SEQUENCE-stage scripts -----------

CREATE SEQUENCE IF NOT EXISTS jeffdm.mdrs_22b36$
INCREMENT BY 1
START WITH 1
MAXVALUE 9223372036854775807
MINVALUE 1
NO CYCLE
CACHE 100;

CREATE SEQUENCE IF NOT EXISTS jeffdm.mdrs_22b4d$
INCREMENT BY 1
START WITH 1
MAXVALUE 9223372036854775807
MINVALUE 1
NO CYCLE
CACHE 100;

-- ------------ Write CREATE-TABLE-stage scripts -----------

CREATE TABLE jeffdm.esrifeatureclass(
    objectid BIGINT GENERATED BY DEFAULT AS IDENTITY( MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20),
    shape GEOMETRY,
    id NUMERIC(38,0),
    ident TEXT,
    type TEXT,
    latitude NUMERIC(38,8),
    longitude NUMERIC(38,8),
    municipality TEXT
)
        WITH (
        OIDS=FALSE
        );

CREATE TABLE jeffdm.gdelttest(
    objectid BIGINT GENERATED BY DEFAULT AS IDENTITY( MAXVALUE 9223372036854775807 MINVALUE 1 NO CYCLE CACHE 20),
    shape GEOMETRY,
    globaleventid CHARACTER VARYING(256),
    actor1code CHARACTER VARYING(256),
    actor1name CHARACTER VARYING(256),
    actor1countrycode CHARACTER VARYING(256)
)
        WITH (
        OIDS=FALSE
        );

CREATE TABLE jeffdm.mdrt_22b36$(
    node_id DOUBLE PRECISION,
    node_level DOUBLE PRECISION,
    info BYTEA
)
        WITH (
        OIDS=FALSE
        );

CREATE TABLE jeffdm.mdrt_22b4d$(
    node_id DOUBLE PRECISION,
    node_level DOUBLE PRECISION,
    info BYTEA
)
        WITH (
        OIDS=FALSE
        );

-- ------------ Write CREATE-INDEX-stage scripts -----------

CREATE INDEX shape_142114_2_sidx
ON jeffdm.esrifeatureclass
USING GIST (shape);

CREATE INDEX shape_142143_2_sidx
ON jeffdm.gdelttest
USING GIST (shape);

CREATE UNIQUE INDEX mdrt22b36_idx1
ON jeffdm.mdrt_22b36$
USING BTREE (node_id ASC);

CREATE UNIQUE INDEX mdrt22b4d_idx1
ON jeffdm.mdrt_22b4d$
USING BTREE (node_id ASC);

-- ------------ Write CREATE-CONSTRAINT-stage scripts -----------

ALTER TABLE jeffdm.esrifeatureclass
ADD PRIMARY KEY (objectid);

ALTER TABLE jeffdm.gdelttest
ADD PRIMARY KEY (objectid);


