ALTER TABLE RESERVATION ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE EMPLOYEE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE airline ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE airport ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

